# Generated by Django 4.0.6 on 2022-07-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('order', '0015_remove_orderproduct_color_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Completed', 'Completed'), ('New', 'New'), ('Cancelled', 'Cancelled')], default='New', max_length=20),
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='Variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='Variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
